name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Stop service
        run: servy-cli stop --name="la-fragancia-astro"
        continue-on-error: true

      - name: Copy only server file
        shell: powershell
        run: |
          Copy-Item `
            "$env:GITHUB_WORKSPACE\server.mjs" `
            "C:\Users\YOLIMA\Workspace\apps\la-fragancia-jm-astro\server.mjs" `
            -Force

      - name: Start service
        run: servy-cli start --name="la-fragancia-astro"
