name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Stop service
        run: servy-cli stop --name="la-fragancia-astro"
        continue-on-error: true

      - name: Copy files
        shell: powershell
        run: |
          robocopy `
            "$env:GITHUB_WORKSPACE" `
            "C:\Users\YOLIMA\Workspace\la-fragancia-jm-astro" `
            server.mjs

      - name: Start service
        run: servy-cli start --name="la-fragancia-astro"
      - name: Verify deployment
        run: |
          $response = Invoke-WebRequest -Uri "http://localhost:3000" -UseBasicParsing
          if ($response.StatusCode -ne 200) {
            throw "Deployment failed: Service is not responding with status code 200."
          }
          Write-Host "Deployment successful: Service is responding with status code 200."
